### ISSUE TITLE
Travis & AppVeyor deployment for releases

### ISSUE THREAD

**Issue by jangler** [schismtracker/schismtracker#40]
me need figure out how do this

**Comment by asbjornu** [comment]
For [Travis, it seems like something along the following lines should work](https://docs.travis-ci.com/user/deployment/):

``` yaml
deploy:
  provider: releases
  api_key: "<GitHub OAuth Token>"
  file: "schismtracker"
  skip_cleanup: true
  on:
    tags: true
    branch: master
```

It will only work out of the box for Linux builds, though, since the OS X build will require an `xcodebuild` step that is currently missing (see #42). For [AppVeyor, something like this should do it](https://www.appveyor.com/docs/deployment/github/):

``` yaml
deploy:
  release: v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: "<encrypted GitHub OAuth Token>"
  artifact: "schismtracker.exe"
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
```
